// <auto-generated />
using System;
using E_Commerce.Infreastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_Commerce.Infreastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("E_Commerce.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Books"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Name = "Home & Kitchen"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Name = "Sports & Outdoors"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Name = "Toys & Games"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Name = "Beauty & Personal Care"
                        });
                });

            modelBuilder.Entity("E_Commerce.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quentity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "15.6 inch Full HD display, Intel Core i5, 8GB RAM, 256GB SSD",
                            Image = "laptop-hp.jpg",
                            Name = "Laptop HP Pavilion",
                            Price = 699.99m,
                            Quentity = 25
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "128GB, Titanium finish, A17 Pro chip",
                            Image = "iphone-15-pro.jpg",
                            Name = "iPhone 15 Pro",
                            Price = 999.99m,
                            Quentity = 50
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "55 inch QLED display",
                            Image = "samsung-tv.jpg",
                            Name = "Samsung 4K Smart TV",
                            Price = 799.99m,
                            Quentity = 15
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Genuine leather, black color",
                            Image = "leather-jacket.jpg",
                            Name = "Men's Leather Jacket",
                            Price = 149.99m,
                            Quentity = 30
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Floral print, cotton blend",
                            Image = "summer-dress.jpg",
                            Name = "Women's Summer Dress",
                            Price = 49.99m,
                            Quentity = 40
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Lightweight, breathable mesh",
                            Image = "nike-shoes.jpg",
                            Name = "Running Shoes Nike",
                            Price = 89.99m,
                            Quentity = 60
                        },
                        new
                        {
                            Id = new Guid("10101010-1010-1010-1010-101010101010"),
                            CategoryId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Description = "Classic novel by F. Scott Fitzgerald",
                            Image = "great-gatsby.jpg",
                            Name = "The Great Gatsby",
                            Price = 15.99m,
                            Quentity = 100
                        },
                        new
                        {
                            Id = new Guid("20202020-2020-2020-2020-202020202020"),
                            CategoryId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Description = "Handbook of Agile Software Craftsmanship",
                            Image = "clean-code.jpg",
                            Name = "Clean Code",
                            Price = 42.99m,
                            Quentity = 75
                        },
                        new
                        {
                            Id = new Guid("30303030-3030-3030-3030-303030303030"),
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Description = "12-cup programmable coffee maker",
                            Image = "coffee-maker.jpg",
                            Name = "Coffee Maker Deluxe",
                            Price = 79.99m,
                            Quentity = 35
                        },
                        new
                        {
                            Id = new Guid("40404040-4040-4040-4040-404040404040"),
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Description = "10-piece set, dishwasher safe",
                            Image = "cookware-set.jpg",
                            Name = "Non-Stick Cookware Set",
                            Price = 129.99m,
                            Quentity = 20
                        },
                        new
                        {
                            Id = new Guid("50505050-5050-5050-5050-505050505050"),
                            CategoryId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Description = "Non-slip, extra thick",
                            Image = "yoga-mat.jpg",
                            Name = "Yoga Mat Premium",
                            Price = 34.99m,
                            Quentity = 80
                        },
                        new
                        {
                            Id = new Guid("60606060-6060-6060-6060-606060606060"),
                            CategoryId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Description = "Waterproof, easy setup",
                            Image = "camping-tent.jpg",
                            Name = "Camping Tent 4-Person",
                            Price = 159.99m,
                            Quentity = 12
                        },
                        new
                        {
                            Id = new Guid("70707070-7070-7070-7070-707070707070"),
                            CategoryId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Description = "Millennium Falcon, 1351 pieces",
                            Image = "lego-starwars.jpg",
                            Name = "LEGO Star Wars Set",
                            Price = 169.99m,
                            Quentity = 45
                        },
                        new
                        {
                            Id = new Guid("80808080-8080-8080-8080-808080808080"),
                            CategoryId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Description = "Strategy game for 3-4 players",
                            Image = "catan.jpg",
                            Name = "Board Game - Catan",
                            Price = 44.99m,
                            Quentity = 55
                        },
                        new
                        {
                            Id = new Guid("90909090-9090-9090-9090-909090909090"),
                            CategoryId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Description = "Hydrating formula with hyaluronic acid",
                            Image = "face-cream.jpg",
                            Name = "Moisturizing Face Cream",
                            Price = 24.99m,
                            Quentity = 90
                        },
                        new
                        {
                            Id = new Guid("a0a0a0a0-a0a0-a0a0-a0a0-a0a0a0a0a0a0"),
                            CategoryId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Description = "Rechargeable, 5 cleaning modes",
                            Image = "electric-toothbrush.jpg",
                            Name = "Electric Toothbrush",
                            Price = 69.99m,
                            Quentity = 40
                        });
                });

            modelBuilder.Entity("E_Commerce.Domain.Entities.Product", b =>
                {
                    b.HasOne("E_Commerce.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("E_Commerce.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
